/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import CollatzEndpointTransport.Linear.CentralRenyiCore
import Mathlib.Analysis.MeanInequalitiesPow
import Mathlib.Analysis.SpecificLimits.Normed

/-!
# Central Renyi Reverse

Reverse recursion for the normalized fixed-total Syracuse lift.

Reading a valuation composition from its final part backwards turns
`3^s + A(k)` into the recursion

  R([]) = 1,
  R(k :: ks) = 3 * R(ks) + 2^(sum ks).

This recursion avoids any reindexing of cumulative suffix sums in the central
higher-Renyi argument.
-/

namespace CollatzEndpointTransport

namespace FixedTotal

open Nat

/-- Integer lift evaluated from the terminal valuation backwards. -/
def reverseLiftNumerator : List ℕ → ℕ
  | [] => 1
  | _k :: ks => 3 * reverseLiftNumerator ks + 2 ^ ks.sum

@[simp]
theorem reverseLiftNumerator_nil : reverseLiftNumerator [] = 1 := rfl

@[simp]
theorem reverseLiftNumerator_cons (k : ℕ) (ks : List ℕ) :
    reverseLiftNumerator (k :: ks) =
      3 * reverseLiftNumerator ks + 2 ^ ks.sum := rfl

/-- Appending the final valuation part gives the matching forward
numerator recursion. -/
theorem syracuseNumeratorList_append_singleton_central
    (ks : List ℕ) (k : ℕ) :
    syracuseNumeratorList (ks ++ [k]) =
      3 * syracuseNumeratorList ks + 2 ^ ks.sum := by
  induction ks with
  | nil => simp
  | cons a ks ih =>
      simp only [List.cons_append, syracuseNumeratorList_cons,
        List.length_append, List.length_singleton, List.sum_cons, ih]
      rw [pow_succ, pow_add]
      ring

/-- Exact prefix/suffix factorization of the Syracuse numerator.

This is the algebraic input for removing a common terminal valuation suffix:
the prefix contribution gains one factor of `3` per suffix block, while the
suffix contribution is shifted by the total dyadic spend of the prefix. -/
theorem syracuseNumeratorList_append_central
    (ks ds : List ℕ) :
    syracuseNumeratorList (ks ++ ds) =
      3 ^ ds.length * syracuseNumeratorList ks +
        2 ^ ks.sum * syracuseNumeratorList ds := by
  induction ks with
  | nil => simp
  | cons k ks ih =>
      simp only [List.cons_append, syracuseNumeratorList_cons,
        List.length_append, List.sum_cons, ih]
      rw [pow_add, pow_add]
      ring

/-- Exact reverse recursion for `3^length + A`. -/
theorem reverseLiftNumerator_reverse_eq (ks : List ℕ) :
    reverseLiftNumerator ks.reverse =
      3 ^ ks.length + syracuseNumeratorList ks := by
  induction ks using List.reverseRecOn with
  | nil => simp
  | append_singleton ks k ih =>
      rw [List.reverse_append, List.reverse_singleton,
        List.singleton_append, reverseLiftNumerator_cons, ih,
        syracuseNumeratorList_append_singleton_central]
      simp only [List.length_append, List.length_singleton,
        List.sum_reverse]
      rw [pow_succ]
      ring

/-- Composition form of the reverse-lift identity. -/
theorem reverseLiftNumerator_composition
    {N : ℕ} (c : Composition N) :
    reverseLiftNumerator c.blocks.reverse =
      3 ^ c.length + syracuseNumerator c := by
  exact reverseLiftNumerator_reverse_eq c.blocks

end FixedTotal

end CollatzEndpointTransport
/-
Concave-power majorant for the reverse fixed-total lift.

The recursive majorant keeps every signed-free contribution generated by
`(a + b)^theta <= a^theta + b^theta`, for `0 < theta <= 1`.  Its terminal
prefixes are exactly the reverse-spend patterns counted in the next module.
-/

namespace CollatzEndpointTransport

namespace FixedTotal

open Nat
open Finset
open scoped NNReal

noncomputable section

/-- Reverse lift divided by its full dyadic spend. -/
def normalizedReverseLift (ks : List ℕ) : ℝ≥0 :=
  (reverseLiftNumerator ks : ℝ≥0) / ((2 : ℝ≥0) ^ ks.sum)

@[simp]
theorem normalizedReverseLift_nil : normalizedReverseLift [] = 1 := by
  simp [normalizedReverseLift]

theorem normalizedReverseLift_cons (k : ℕ) (ks : List ℕ) :
    normalizedReverseLift (k :: ks) =
      (1 + 3 * normalizedReverseLift ks) / ((2 : ℝ≥0) ^ k) := by
  unfold normalizedReverseLift
  simp only [reverseLiftNumerator_cons, List.sum_cons, Nat.cast_add,
    Nat.cast_mul, Nat.cast_ofNat, pow_add]
  have htwo : ((2 : ℝ≥0) ^ ks.sum) ≠ 0 := by positivity
  field_simp
  ring

/-- Recursive concave-power expansion of the normalized reverse lift. -/
def reverseMomentMajorant (theta : ℝ) : List ℕ → ℝ≥0
  | [] => 1
  | k :: ks =>
      (1 + (3 : ℝ≥0) ^ theta * reverseMomentMajorant theta ks) /
        (((2 : ℝ≥0) ^ k) ^ theta)

@[simp]
theorem reverseMomentMajorant_nil (theta : ℝ) :
    reverseMomentMajorant theta [] = 1 := rfl

@[simp]
theorem reverseMomentMajorant_cons (theta : ℝ) (k : ℕ) (ks : List ℕ) :
    reverseMomentMajorant theta (k :: ks) =
      (1 + (3 : ℝ≥0) ^ theta * reverseMomentMajorant theta ks) /
        (((2 : ℝ≥0) ^ k) ^ theta) := rfl

/-- One exposed terminal-prefix contribution in the reverse expansion. -/
def reverseMomentTerm (theta : ℝ) (ks : List ℕ) (i : ℕ) : ℝ≥0 :=
  ((3 : ℝ≥0) ^ theta) ^ i /
    (((2 : ℝ≥0) ^ (ks.take (i + 1)).sum) ^ theta)

/-- Closed prefix-spend expansion of the recursive majorant. -/
def reverseMomentSeries (theta : ℝ) (ks : List ℕ) : ℝ≥0 :=
  (∑ i ∈ range ks.length, reverseMomentTerm theta ks i) +
    ((3 : ℝ≥0) ^ theta) ^ ks.length /
      (((2 : ℝ≥0) ^ ks.sum) ^ theta)

theorem reverseMomentTerm_cons_zero
    (theta : ℝ) (k : ℕ) (ks : List ℕ) :
    reverseMomentTerm theta (k :: ks) 0 =
      1 / (((2 : ℝ≥0) ^ k) ^ theta) := by
  simp [reverseMomentTerm]

theorem reverseMomentTerm_cons_succ
    (theta : ℝ) (k : ℕ) (ks : List ℕ) (i : ℕ) :
    reverseMomentTerm theta (k :: ks) (i + 1) =
      ((3 : ℝ≥0) ^ theta) /
          (((2 : ℝ≥0) ^ k) ^ theta) *
        reverseMomentTerm theta ks i := by
  unfold reverseMomentTerm
  simp only [List.take_succ_cons, List.sum_cons, pow_succ, pow_add,
    NNReal.mul_rpow]
  have hk : (((2 : ℝ≥0) ^ k) ^ theta) ≠ 0 :=
    (NNReal.rpow_pos (by positivity)).ne'
  have hi : (((2 : ℝ≥0) ^ (ks.take (i + 1)).sum) ^ theta) ≠ 0 :=
    (NNReal.rpow_pos (by positivity)).ne'
  field_simp
  ring

theorem reverseMoment_tail_cons
    (theta : ℝ) (k : ℕ) (ks : List ℕ) :
    ((3 : ℝ≥0) ^ theta) ^ (k :: ks).length /
        (((2 : ℝ≥0) ^ (k :: ks).sum) ^ theta) =
      ((3 : ℝ≥0) ^ theta) /
          (((2 : ℝ≥0) ^ k) ^ theta) *
        (((3 : ℝ≥0) ^ theta) ^ ks.length /
          (((2 : ℝ≥0) ^ ks.sum) ^ theta)) := by
  simp only [List.length_cons, List.sum_cons, pow_succ, pow_add,
    NNReal.mul_rpow]
  have hk : (((2 : ℝ≥0) ^ k) ^ theta) ≠ 0 :=
    (NNReal.rpow_pos (by positivity)).ne'
  have hs : (((2 : ℝ≥0) ^ ks.sum) ^ theta) ≠ 0 :=
    (NNReal.rpow_pos (by positivity)).ne'
  field_simp
  ring

theorem reverseMomentMajorant_eq_series (theta : ℝ) :
    ∀ ks : List ℕ,
      reverseMomentMajorant theta ks = reverseMomentSeries theta ks := by
  intro ks
  induction ks with
  | nil => simp [reverseMomentSeries]
  | cons k ks ih =>
      rw [reverseMomentMajorant_cons, reverseMomentSeries]
      rw [reverseMoment_tail_cons]
      simp only [List.length_cons]
      rw [Finset.sum_range_succ', reverseMomentTerm_cons_zero]
      rw [Finset.sum_congr rfl (fun i _ => reverseMomentTerm_cons_succ theta k ks i),
        ← Finset.mul_sum, ih, reverseMomentSeries]
      have hk : (((2 : ℝ≥0) ^ k) ^ theta) ≠ 0 :=
        (NNReal.rpow_pos (by positivity)).ne'
      have hs : (((2 : ℝ≥0) ^ ks.sum) ^ theta) ≠ 0 :=
        (NNReal.rpow_pos (by positivity)).ne'
      field_simp
      ring

/-- Pointwise reverse-spend majorization. -/
theorem normalizedReverseLift_rpow_le_majorant
    {theta : ℝ} (htheta0 : 0 ≤ theta) (htheta1 : theta ≤ 1) :
    ∀ ks : List ℕ,
      (normalizedReverseLift ks) ^ theta ≤
        reverseMomentMajorant theta ks := by
  intro ks
  induction ks with
  | nil => simp
  | cons k ks ih =>
      rw [normalizedReverseLift_cons, reverseMomentMajorant_cons,
        NNReal.div_rpow]
      have hden : 0 < (((2 : ℝ≥0) ^ k) ^ theta) :=
        NNReal.rpow_pos (by positivity)
      apply (div_le_div_iff_of_pos_right hden).2
      calc
        (1 + 3 * normalizedReverseLift ks) ^ theta
            ≤ (1 : ℝ≥0) ^ theta +
                (3 * normalizedReverseLift ks) ^ theta :=
          NNReal.rpow_add_le_add_rpow 1 (3 * normalizedReverseLift ks)
            htheta0 htheta1
        _ = 1 + (3 : ℝ≥0) ^ theta *
              (normalizedReverseLift ks) ^ theta := by
          rw [NNReal.one_rpow, NNReal.mul_rpow]
        _ ≤ 1 + (3 : ℝ≥0) ^ theta *
              reverseMomentMajorant theta ks := by
          gcongr

/-- Composition form, tied to the forward Syracuse numerator. -/
theorem normalized_fixed_lift_rpow_le_majorant
    {N : ℕ} (c : Composition N) {theta : ℝ}
    (htheta0 : 0 ≤ theta) (htheta1 : theta ≤ 1) :
    ((((3 ^ c.length + syracuseNumerator c : ℕ) : ℝ≥0) /
          ((2 : ℝ≥0) ^ N)) ^ theta) ≤
      reverseMomentMajorant theta c.blocks.reverse := by
  have hsum : c.blocks.sum = N := c.blocks_sum
  have hid := reverseLiftNumerator_composition c
  simpa [normalizedReverseLift, List.sum_reverse, hsum, hid] using
    normalizedReverseLift_rpow_le_majorant htheta0 htheta1 c.blocks.reverse

end

end FixedTotal

end CollatzEndpointTransport
/-
The central fixed-total reverse-spend estimate.

This file turns the exact terminal-pattern partition into the
negative-binomial majorant for the central reverse-spend estimate. The first
stage records the real-valued terminal term and its exact dependence on
the total spend in the final blocks.
-/

namespace CollatzEndpointTransport

namespace FixedTotal

open Nat Finset
open scoped Real NNReal

noncomputable section

/-- Proportion of separators in the fixed-total composition model. -/
def centralSeparatorProportion (N s : ℕ) : ℝ :=
  ((s - 1 : ℕ) : ℝ) / (N - 1 : ℕ)

/-- The `r`-th exposed reverse-spend contribution, written in `ℝ`. -/
def realReverseMomentTerm
    (theta : ℝ) {N : ℕ} (c : Composition N) (r : ℕ) : ℝ :=
  (((3 : ℝ) ^ theta) ^ (r - 1)) /
    (((2 : ℝ) ^ reverseSpend c r) ^ theta)

theorem coe_reverseMomentTerm_eq_realReverseMomentTerm
    {theta : ℝ} {N : ℕ} (c : Composition N) {r : ℕ} (hr : 0 < r) :
    (reverseMomentTerm theta c.blocks.reverse (r - 1) : ℝ) =
      realReverseMomentTerm theta c r := by
  unfold reverseMomentTerm realReverseMomentTerm
  rw [Nat.sub_add_cancel hr]
  rw [sum_take_reverse_eq_reverseSpend]
  norm_cast

theorem realReverseMomentTerm_nonneg
    (theta : ℝ) {N : ℕ} (c : Composition N) (r : ℕ) :
    0 ≤ realReverseMomentTerm theta c r := by
  unfold realReverseMomentTerm
  positivity

/-- The terminal term depends only on the terminal block list. -/
def realTerminalPatternTerm (theta : ℝ) (r : ℕ) (d : List ℕ) : ℝ :=
  (((3 : ℝ) ^ theta) ^ (r - 1)) /
    (((2 : ℝ) ^ d.sum) ^ theta)

/-- The common value of the terminal term on a fixed-spend slice. -/
def realTerminalSpendTerm (theta : ℝ) (r D : ℕ) : ℝ :=
  (((3 : ℝ) ^ theta) ^ (r - 1)) /
    (((2 : ℝ) ^ D) ^ theta)

theorem realTerminalSpendTerm_nonneg
    (theta : ℝ) (r D : ℕ) :
    0 ≤ realTerminalSpendTerm theta r D := by
  unfold realTerminalSpendTerm
  positivity

theorem realReverseMomentTerm_eq_pattern
    (theta : ℝ) {N : ℕ} (c : Composition N) (r : ℕ) :
    realReverseMomentTerm theta c r =
      realTerminalPatternTerm theta r (terminalBlocks c r) := by
  simp [realReverseMomentTerm, realTerminalPatternTerm, reverseSpend]

/-- Sum of one reverse-spend term over a fixed composition level. -/
def fixedReverseTermSum (N s : ℕ) (theta : ℝ) (r : ℕ) : ℝ :=
  ∑ c ∈ fixedSet N s, realReverseMomentTerm theta c r

theorem fixedReverseTermSum_nonneg
    (N s : ℕ) (theta : ℝ) (r : ℕ) :
    0 ≤ fixedReverseTermSum N s theta r := by
  unfold fixedReverseTermSum
  exact sum_nonneg fun c _ => realReverseMomentTerm_nonneg theta c r

/-- Exact partition of one reverse-spend sum by the terminal block list. -/
theorem fixedReverseTermSum_eq_terminalPatterns
    (N s : ℕ) (theta : ℝ) (r : ℕ) :
    fixedReverseTermSum N s theta r =
      ∑ d ∈ terminalPatternImage N s r,
        (terminalFiber N s r d).card *
          realTerminalPatternTerm theta r d := by
  unfold fixedReverseTermSum
  simp_rw [realReverseMomentTerm_eq_pattern]
  exact sum_by_terminalBlocks
    (R := ℝ) (N := N) (s := s) (r := r)
      (realTerminalPatternTerm theta r)

/-- Exact further partition by the total terminal spend. -/
theorem fixedReverseTermSum_eq_spend
    (N s : ℕ) (theta : ℝ) (r : ℕ) :
    fixedReverseTermSum N s theta r =
      ∑ D ∈ range (N + 1),
        ∑ d ∈ terminalPatternSet N s r D,
          (terminalFiber N s r d).card *
            realTerminalPatternTerm theta r d := by
  rw [fixedReverseTermSum_eq_terminalPatterns]
  simpa using
    (sum_terminalPatterns_by_spend
      (R := ℝ) (N := N) (s := s) (r := r)
      (fun _D d =>
        (terminalFiber N s r d).card *
          realTerminalPatternTerm theta r d))

/-- One fixed-spend slice is bounded by the product of its possible
terminal patterns and compatible prefixes. -/
theorem terminalSpendSlice_le
    {N s r D : ℕ} (theta : ℝ)
    (hr0 : 0 < r) (hrs : r < s) :
    (∑ d ∈ terminalPatternSet N s r D,
        (terminalFiber N s r d).card *
          realTerminalPatternTerm theta r d) ≤
      ((D - 1).choose (r - 1) : ℝ) *
        ((N - D - 1).choose (s - r - 1) : ℝ) *
          realTerminalSpendTerm theta r D := by
  by_cases hempty : terminalPatternSet N s r D = ∅
  · rw [hempty]
    simp only [sum_empty]
    exact mul_nonneg (mul_nonneg (by positivity) (by positivity))
      (realTerminalSpendTerm_nonneg theta r D)
  · obtain ⟨d, hd⟩ := Finset.nonempty_iff_ne_empty.mpr hempty
    have hD0 := terminalPatternSet_spend_pos hr0 hrs.le hd
    have hDN := terminalPatternSet_spend_lt hrs hd
    have hprefixTotal : 0 < N - D := Nat.sub_pos_of_lt hDN
    have hprefixLength : 0 < s - r := Nat.sub_pos_of_lt hrs
    have hpatterns := card_terminalPatternSet_le_choose
      (N := N) (s := s) (D := D) hrs.le hD0 hr0
    have hweight : 0 ≤ realTerminalSpendTerm theta r D :=
      realTerminalSpendTerm_nonneg theta r D
    calc
      (∑ d ∈ terminalPatternSet N s r D,
          (terminalFiber N s r d).card *
            realTerminalPatternTerm theta r d) ≤
          ∑ _d ∈ terminalPatternSet N s r D,
            ((N - D - 1).choose (s - r - 1) : ℝ) *
              realTerminalSpendTerm theta r D := by
        apply sum_le_sum
        intro d hd
        have hdSum := (Finset.mem_filter.mp hd).2
        have hprefixTotalD : 0 < N - d.sum := by
          simpa [hdSum] using hprefixTotal
        have hfiber := card_terminalFiber_le_choose d
          hprefixTotalD hprefixLength
        have hfiberR :
            ((terminalFiber N s r d).card : ℝ) ≤
              ((N - D - 1).choose (s - r - 1) : ℝ) := by
          simpa [hdSum] using (show
            ((terminalFiber N s r d).card : ℝ) ≤
              (((N - d.sum - 1).choose (s - r - 1) : ℕ) : ℝ) by
                exact_mod_cast hfiber)
        have hterm :
            realTerminalPatternTerm theta r d =
              realTerminalSpendTerm theta r D := by
          simp [realTerminalPatternTerm, realTerminalSpendTerm, hdSum]
        rw [hterm]
        exact mul_le_mul_of_nonneg_right hfiberR hweight
      _ = ((terminalPatternSet N s r D).card : ℝ) *
          (((N - D - 1).choose (s - r - 1) : ℝ) *
            realTerminalSpendTerm theta r D) := by
        simp
      _ ≤ ((D - 1).choose (r - 1) : ℝ) *
          (((N - D - 1).choose (s - r - 1) : ℝ) *
            realTerminalSpendTerm theta r D) := by
        have hpatternsR :
            ((terminalPatternSet N s r D).card : ℝ) ≤
              ((D - 1).choose (r - 1) : ℝ) := by
          exact_mod_cast hpatterns
        exact mul_le_mul_of_nonneg_right hpatternsR (by positivity)
      _ = ((D - 1).choose (r - 1) : ℝ) *
          ((N - D - 1).choose (s - r - 1) : ℝ) *
            realTerminalSpendTerm theta r D := by ring

/-- Conditional probability form of the fixed-spend estimate. -/
theorem terminalSpendSlice_div_card_le
    {N s r D : ℕ} (theta : ℝ)
    (hN : 1 < N) (hs1 : 1 < s) (hsN : s < N)
    (hr0 : 0 < r) (hrs : r < s) :
    (∑ d ∈ terminalPatternSet N s r D,
        (terminalFiber N s r d).card *
          realTerminalPatternTerm theta r d) /
          ((fixedSet N s).card : ℝ) ≤
      (N : ℝ) *
        centralSeparatorProportion N s ^ r *
        (1 - centralSeparatorProportion N s) ^ (D - r) *
        ((D - 1).choose (r - 1) : ℝ) *
        realTerminalSpendTerm theta r D := by
  have hcard : 0 < ((fixedSet N s).card : ℝ) := by
    rw [card_fixedSet N s (by omega) (by omega)]
    exact_mod_cast Nat.choose_pos (by omega : s - 1 ≤ N - 1)
  have hpi0 : 0 ≤ centralSeparatorProportion N s := by
    unfold centralSeparatorProportion
    positivity
  have hpi1 : centralSeparatorProportion N s ≤ 1 := by
    unfold centralSeparatorProportion
    have hNm1 : 0 < (N - 1 : ℕ) := by omega
    apply (div_le_one (by exact_mod_cast hNm1 : (0 : ℝ) < (N - 1 : ℕ))).2
    exact_mod_cast (by omega : s - 1 ≤ N - 1)
  have hq0 : 0 ≤ 1 - centralSeparatorProportion N s := sub_nonneg.mpr hpi1
  by_cases hempty : terminalPatternSet N s r D = ∅
  · rw [hempty]
    simp only [sum_empty, zero_div]
    exact mul_nonneg
      (mul_nonneg
        (mul_nonneg
          (mul_nonneg (Nat.cast_nonneg N) (pow_nonneg hpi0 _))
          (pow_nonneg hq0 _))
        (Nat.cast_nonneg _))
      (realTerminalSpendTerm_nonneg theta r D)
  · obtain ⟨d, hd⟩ := Finset.nonempty_iff_ne_empty.mpr hempty
    have hD0 := terminalPatternSet_spend_pos hr0 hrs.le hd
    have hDN := terminalPatternSet_spend_lt hrs hd
    obtain ⟨hrD, hprefixSpend⟩ :=
      terminalPatternSet_spend_bounds hrs.le hd
    have hratio := terminal_choose_ratio_le
      (n := N - 1) (k := s - 1) (D := D) (r := r)
      (by omega) (by omega) (by omega) (by omega) hrD (by omega)
    have hprefixIndex :
        (N - 1 - D).choose (s - 1 - r) =
          (N - D - 1).choose (s - r - 1) := by
      congr 1 <;> omega
    have htotalIndex :
        (N - 1).choose (s - 1) = (fixedSet N s).card := by
      rw [card_fixedSet N s (by omega) (by omega)]
    have hq :
        (((N - 1 - (s - 1) : ℕ) : ℝ) / (N - 1 : ℕ)) =
          1 - centralSeparatorProportion N s := by
      rw [show N - 1 - (s - 1) = N - s by omega]
      unfold centralSeparatorProportion
      rw [Nat.cast_sub hsN.le, Nat.cast_sub (by omega : 1 ≤ N),
        Nat.cast_sub (by omega : 1 ≤ s)]
      have hNreal : (1 : ℝ) < N := by exact_mod_cast hN
      field_simp [show (N : ℝ) - 1 ≠ 0 by linarith]
    rw [hprefixIndex, htotalIndex, hq] at hratio
    have hratio' :
        ((N - D - 1).choose (s - r - 1) : ℝ) /
            ((fixedSet N s).card : ℝ) ≤
          (N : ℝ) * centralSeparatorProportion N s ^ r *
            (1 - centralSeparatorProportion N s) ^ (D - r) := by
      simpa [centralSeparatorProportion,
        Nat.cast_sub (by omega : 1 ≤ N),
        Nat.cast_sub (by omega : 1 ≤ s)] using hratio
    have hprefixBound :
        ((N - D - 1).choose (s - r - 1) : ℝ) ≤
          ((N : ℝ) * centralSeparatorProportion N s ^ r *
            (1 - centralSeparatorProportion N s) ^ (D - r)) *
              ((fixedSet N s).card : ℝ) :=
      (div_le_iff₀ hcard).mp hratio'
    have hslice := terminalSpendSlice_le
      (N := N) (s := s) (r := r) (D := D) theta hr0 hrs
    apply (div_le_iff₀ hcard).2
    calc
      (∑ d ∈ terminalPatternSet N s r D,
          (terminalFiber N s r d).card *
            realTerminalPatternTerm theta r d) ≤
          ((D - 1).choose (r - 1) : ℝ) *
            ((N - D - 1).choose (s - r - 1) : ℝ) *
              realTerminalSpendTerm theta r D := hslice
      _ ≤ ((D - 1).choose (r - 1) : ℝ) *
          ((N : ℝ) * centralSeparatorProportion N s ^ r *
            (1 - centralSeparatorProportion N s) ^ (D - r) *
              ((fixedSet N s).card : ℝ)) *
            realTerminalSpendTerm theta r D := by
        exact mul_le_mul_of_nonneg_right
          (mul_le_mul_of_nonneg_left hprefixBound (Nat.cast_nonneg _))
          (realTerminalSpendTerm_nonneg theta r D)
      _ = ((N : ℝ) * centralSeparatorProportion N s ^ r *
          (1 - centralSeparatorProportion N s) ^ (D - r) *
          ((D - 1).choose (r - 1) : ℝ) *
          realTerminalSpendTerm theta r D) *
            ((fixedSet N s).card : ℝ) := by ring

end

end FixedTotal

end CollatzEndpointTransport
/-
Negative-binomial summation for the central reverse-spend bound.

The terminal composition estimate leaves a finite sum over the excess
spend `n = D - r`.  This file evaluates the corresponding infinite
majorant exactly and identifies its ratio with `centralRenyiRatio`.
-/

namespace CollatzEndpointTransport

namespace FixedTotal

open Nat Finset
open scoped Real

noncomputable section

/-- Ratio of one additional unit of reverse spend after the terminal
separator pattern has been fixed. -/
def centralReverseTailRatio (theta pi : ℝ) : ℝ :=
  (1 - pi) / (2 : ℝ) ^ theta

theorem centralReverseTailRatio_nonneg
    {theta pi : ℝ} (hpi1 : pi ≤ 1) :
    0 ≤ centralReverseTailRatio theta pi := by
  unfold centralReverseTailRatio
  exact div_nonneg (sub_nonneg.mpr hpi1)
    (Real.rpow_nonneg (by norm_num) theta)

theorem centralReverseTailRatio_lt_one
    {theta pi : ℝ} (htheta : 0 < theta)
    (hpi0 : 0 ≤ pi) :
    centralReverseTailRatio theta pi < 1 := by
  unfold centralReverseTailRatio
  have htwo : 1 < (2 : ℝ) ^ theta := one_lt_two_rpow htheta
  rw [div_lt_one (by positivity : 0 < (2 : ℝ) ^ theta)]
  linarith

theorem norm_centralReverseTailRatio_lt_one
    {theta pi : ℝ} (htheta : 0 < theta)
    (hpi0 : 0 ≤ pi) (hpi1 : pi ≤ 1) :
    ‖centralReverseTailRatio theta pi‖ < 1 := by
  rw [Real.norm_eq_abs, abs_of_nonneg
    (centralReverseTailRatio_nonneg hpi1)]
  exact centralReverseTailRatio_lt_one htheta hpi0

/-- Exact negative-binomial generating series. -/
theorem tsum_shifted_choose_mul_geometric
    {q : ℝ} (r : ℕ) (hr : 0 < r) (hq : ‖q‖ < 1) :
    ∑' n : ℕ, ((n + r - 1).choose (r - 1) : ℝ) * q ^ n =
      1 / (1 - q) ^ r := by
  have hbase := tsum_choose_mul_geometric_of_norm_lt_one
    (r - 1) hq
  simpa [Nat.add_sub_assoc (by omega : 1 ≤ r),
    Nat.sub_add_cancel (by omega : 1 ≤ r)] using hbase

/-- Raising a natural power and then taking a real power commutes for a
nonnegative base. -/
theorem natPow_rpow_eq_rpow_natPow
    {x : ℝ} (hx : 0 ≤ x) (n : ℕ) (theta : ℝ) :
    (x ^ n) ^ theta = (x ^ theta) ^ n := by
  rw [← Real.rpow_natCast, ← Real.rpow_mul hx,
    mul_comm, Real.rpow_mul hx, Real.rpow_natCast]

/-- The fixed-spend terminal term with `D = r+n` factors into the
negative-binomial tail ratio. -/
theorem shifted_terminal_majorant_eq
    {theta pi : ℝ} {r n : ℕ} (hr : 0 < r) :
    pi ^ r * (1 - pi) ^ n *
          ((n + r - 1).choose (r - 1) : ℝ) *
          realTerminalSpendTerm theta r (n + r) =
      (3 : ℝ) ^ (-theta) *
        (((3 : ℝ) ^ theta * pi / (2 : ℝ) ^ theta) ^ r) *
        (((n + r - 1).choose (r - 1) : ℝ) *
          centralReverseTailRatio theta pi ^ n) := by
  have htwo : (0 : ℝ) ≤ 2 := by norm_num
  have hthree : (0 : ℝ) ≤ 3 := by norm_num
  have htwoPos : (0 : ℝ) < (2 : ℝ) ^ theta := by positivity
  have hthreePos : (0 : ℝ) < (3 : ℝ) ^ theta := by positivity
  rw [show n + r = r + n by omega]
  unfold realTerminalSpendTerm centralReverseTailRatio
  rw [pow_add, Real.mul_rpow (by positivity) (by positivity),
    natPow_rpow_eq_rpow_natPow htwo,
    natPow_rpow_eq_rpow_natPow htwo]
  have hthreeNe : (3 : ℝ) ^ theta ≠ 0 := hthreePos.ne'
  have hpowThree :
      ((3 : ℝ) ^ theta) ^ (r - 1) =
        ((3 : ℝ) ^ theta) ^ r / (3 : ℝ) ^ theta := by
    calc
      ((3 : ℝ) ^ theta) ^ (r - 1) =
          (((3 : ℝ) ^ theta) ^ (r - 1) * (3 : ℝ) ^ theta) /
            (3 : ℝ) ^ theta := by field_simp
      _ = ((3 : ℝ) ^ theta) ^ r / (3 : ℝ) ^ theta := by
        rw [← pow_succ, Nat.sub_add_cancel (by omega : 1 ≤ r)]
  rw [hpowThree, Real.rpow_neg (by norm_num : (0 : ℝ) ≤ 3)]
  field_simp
  ring

theorem summable_terminal_majorant
    {theta pi : ℝ} {r : ℕ}
    (htheta : 0 < theta) (hpi0 : 0 ≤ pi) (hpi1 : pi ≤ 1)
    (hr : 0 < r) :
    Summable fun n : ℕ =>
      pi ^ r * (1 - pi) ^ n *
        ((n + r - 1).choose (r - 1) : ℝ) *
        realTerminalSpendTerm theta r (n + r) := by
  have hq := norm_centralReverseTailRatio_lt_one htheta hpi0 hpi1
  have hs := summable_choose_mul_geometric_of_norm_lt_one (r - 1) hq
  have hs' : Summable fun n : ℕ =>
      ((n + r - 1).choose (r - 1) : ℝ) *
        centralReverseTailRatio theta pi ^ n := by
    simpa [Nat.add_sub_assoc (by omega : 1 ≤ r)] using hs
  simpa only [shifted_terminal_majorant_eq
    (theta := theta) (pi := pi) hr] using
      hs'.mul_left ((3 : ℝ) ^ (-theta) *
        (((3 : ℝ) ^ theta * pi / (2 : ℝ) ^ theta) ^ r))

/-- Closed form of the negative-binomial terminal majorant. -/
theorem tsum_terminal_majorant
    {theta pi : ℝ} {r : ℕ}
    (htheta : 0 < theta) (hpi0 : 0 ≤ pi) (hpi1 : pi ≤ 1)
    (hr : 0 < r) :
    ∑' n : ℕ,
        pi ^ r * (1 - pi) ^ n *
          ((n + r - 1).choose (r - 1) : ℝ) *
          realTerminalSpendTerm theta r (n + r) =
      (3 : ℝ) ^ (-theta) *
        centralRenyiRatio theta pi ^ r := by
  have hq := norm_centralReverseTailRatio_lt_one htheta hpi0 hpi1
  simp_rw [shifted_terminal_majorant_eq (theta := theta) (pi := pi) hr]
  rw [tsum_mul_left]
  rw [tsum_shifted_choose_mul_geometric r hr hq]
  unfold centralRenyiRatio centralReverseTailRatio
  have htwo : 0 < (2 : ℝ) ^ theta := by positivity
  have hden : 0 < (2 : ℝ) ^ theta - 1 + pi := by
    linarith [one_lt_two_rpow htheta]
  rw [show 1 - (1 - pi) / (2 : ℝ) ^ theta =
      ((2 : ℝ) ^ theta - 1 + pi) / (2 : ℝ) ^ theta by
        field_simp
        ring]
  field_simp

/-- One nonterminal reverse-spend term, averaged over a fixed composition
level, is bounded by the exact geometric ratio from the paper. -/
theorem fixedReverseTermSum_div_card_le
    {N s r : ℕ} {theta : ℝ}
    (htheta : 0 < theta)
    (hN : 1 < N) (hs1 : 1 < s) (hsN : s < N)
    (hr0 : 0 < r) (hrs : r < s) :
    fixedReverseTermSum N s theta r / ((fixedSet N s).card : ℝ) ≤
      (N : ℝ) * (3 : ℝ) ^ (-theta) *
        centralRenyiRatio theta (centralSeparatorProportion N s) ^ r := by
  let pi := centralSeparatorProportion N s
  let g : ℕ → ℝ := fun n =>
    pi ^ r * (1 - pi) ^ n *
      ((n + r - 1).choose (r - 1) : ℝ) *
      realTerminalSpendTerm theta r (n + r)
  have hpi0 : 0 ≤ pi := by
    dsimp [pi, centralSeparatorProportion]
    positivity
  have hpi1 : pi ≤ 1 := by
    dsimp [pi, centralSeparatorProportion]
    have hNm1 : 0 < (N - 1 : ℕ) := by omega
    apply (div_le_one (by exact_mod_cast hNm1 : (0 : ℝ) < (N - 1 : ℕ))).2
    exact_mod_cast (by omega : s - 1 ≤ N - 1)
  have hg0 : ∀ n, 0 ≤ g n := by
    intro n
    dsimp [g]
    exact mul_nonneg
      (mul_nonneg
        (mul_nonneg (pow_nonneg hpi0 _) (pow_nonneg (sub_nonneg.mpr hpi1) _))
        (Nat.cast_nonneg _))
      (realTerminalSpendTerm_nonneg theta r (n + r))
  have hgsum : Summable g := by
    simpa [g] using
      (summable_terminal_majorant
        (theta := theta) (pi := pi) (r := r) htheta hpi0 hpi1 hr0)
  rw [fixedReverseTermSum_eq_spend, Finset.sum_div]
  calc
    (∑ D ∈ range (N + 1),
        (∑ d ∈ terminalPatternSet N s r D,
          (terminalFiber N s r d).card *
            realTerminalPatternTerm theta r d) /
              ((fixedSet N s).card : ℝ)) ≤
        ∑ D ∈ range (N + 1),
          if r ≤ D then (N : ℝ) * g (D - r) else 0 := by
      apply sum_le_sum
      intro D hD
      by_cases hrD : r ≤ D
      · rw [if_pos hrD]
        have hslice := terminalSpendSlice_div_card_le
          (N := N) (s := s) (r := r) (D := D) theta
          hN hs1 hsN hr0 hrs
        calc
          (∑ d ∈ terminalPatternSet N s r D,
              (terminalFiber N s r d).card *
                realTerminalPatternTerm theta r d) /
                ((fixedSet N s).card : ℝ) ≤
              (N : ℝ) * centralSeparatorProportion N s ^ r *
                (1 - centralSeparatorProportion N s) ^ (D - r) *
                ((D - 1).choose (r - 1) : ℝ) *
                realTerminalSpendTerm theta r D := hslice
          _ = (N : ℝ) * g (D - r) := by
            simp only [g, pi, Nat.sub_add_cancel hrD]
            ring
      · have hDr : D < r := Nat.lt_of_not_ge hrD
        have hempty := terminalPatternSet_eq_empty_of_spend_lt
          (N := N) hrs.le hDr
        rw [hempty, if_neg hrD]
        simp
    _ = ∑ D ∈ Ico r (N + 1), (N : ℝ) * g (D - r) := by
      rw [← Finset.sum_filter]
      apply Finset.sum_congr
      · ext D
        simp [and_comm]
      · intro D hD
        rfl
    _ = ∑ n ∈ range (N + 1 - r), (N : ℝ) * g n := by
      rw [Finset.sum_Ico_eq_sum_range]
      apply sum_congr rfl
      intro n hn
      rw [Nat.add_sub_cancel_left]
    _ ≤ (N : ℝ) * ∑' n : ℕ, g n := by
      rw [← Finset.mul_sum]
      exact mul_le_mul_of_nonneg_left
        (sum_le_tsum (s := range (N + 1 - r))
          (fun n _ => hg0 n) hgsum)
        (Nat.cast_nonneg N)
    _ = (N : ℝ) * (3 : ℝ) ^ (-theta) *
        centralRenyiRatio theta (centralSeparatorProportion N s) ^ r := by
      have htsum := tsum_terminal_majorant
        (theta := theta) (pi := pi) (r := r)
        htheta hpi0 hpi1 hr0
      rw [htsum]
      simp only [pi]
      ring

end

end FixedTotal

end CollatzEndpointTransport
/-
Central reverse-spend average.

This module sums the fixed-terminal-spend estimate over every nonterminal
reverse prefix.  The geometric denominator is finite precisely below the
central Renyi threshold.
-/

namespace CollatzEndpointTransport

namespace FixedTotal

open Nat Finset
open scoped Real NNReal

noncomputable section

/-- Sum of the nonterminal reverse-prefix contributions on one fixed
composition level. -/
def fixedReverseNonterminalSum
    (N s : ℕ) (theta : ℝ) : ℝ :=
  ∑ r ∈ Ico 1 s, fixedReverseTermSum N s theta r

theorem centralRenyiRatio_nonneg
    {theta pi : ℝ} (htheta : 0 < theta) (hpi : 0 ≤ pi) :
    0 ≤ centralRenyiRatio theta pi := by
  unfold centralRenyiRatio
  have hden : 0 < (2 : ℝ) ^ theta - 1 + pi := by
    linarith [one_lt_two_rpow htheta]
  exact div_nonneg (mul_nonneg (Real.rpow_nonneg (by norm_num) _) hpi)
    hden.le

/-- The complete nonterminal reverse-spend average is bounded by a
geometric series.  Including the harmless `r = 0` term keeps the formal
constant simple. -/
theorem fixedReverseNonterminalSum_div_card_le
    {N s : ℕ} {theta : ℝ}
    (htheta : 0 < theta)
    (hN : 1 < N) (hs1 : 1 < s) (hsN : s < N)
    (hpiAlpha :
      centralSeparatorProportion N s < centralRenyiAlpha theta) :
    fixedReverseNonterminalSum N s theta /
        ((fixedSet N s).card : ℝ) ≤
      (N : ℝ) * (3 : ℝ) ^ (-theta) /
        (1 - centralRenyiRatio theta
          (centralSeparatorProportion N s)) := by
  let R := centralRenyiRatio theta (centralSeparatorProportion N s)
  have hpi0 : 0 < centralSeparatorProportion N s := by
    unfold centralSeparatorProportion
    have hsPos : 0 < (s - 1 : ℕ) := by omega
    have hNPos : 0 < (N - 1 : ℕ) := by omega
    exact div_pos (by exact_mod_cast hsPos) (by exact_mod_cast hNPos)
  have hR0 : 0 ≤ R := centralRenyiRatio_nonneg htheta hpi0.le
  have hR1 : R < 1 :=
    centralRenyiRatio_lt_one htheta hpi0 hpiAlpha
  have hsummable : Summable fun r : ℕ =>
      (N : ℝ) * (3 : ℝ) ^ (-theta) * R ^ r :=
    (summable_geometric_of_lt_one hR0 hR1).mul_left
      ((N : ℝ) * (3 : ℝ) ^ (-theta))
  unfold fixedReverseNonterminalSum
  rw [Finset.sum_div]
  calc
    (∑ r ∈ Ico 1 s,
        fixedReverseTermSum N s theta r /
          ((fixedSet N s).card : ℝ)) ≤
        ∑ r ∈ Ico 1 s,
          (N : ℝ) * (3 : ℝ) ^ (-theta) * R ^ r := by
      apply sum_le_sum
      intro r hr
      have hrBounds := mem_Ico.mp hr
      simpa [R] using
        (fixedReverseTermSum_div_card_le
          (N := N) (s := s) (r := r) (theta := theta)
          htheta hN hs1 hsN hrBounds.1 hrBounds.2)
    _ ≤ ∑' r : ℕ,
        (N : ℝ) * (3 : ℝ) ^ (-theta) * R ^ r := by
      exact sum_le_tsum (s := Ico 1 s)
        (fun r _ => by positivity) hsummable
    _ = (N : ℝ) * (3 : ℝ) ^ (-theta) /
        (1 - centralRenyiRatio theta
          (centralSeparatorProportion N s)) := by
      rw [tsum_mul_left, tsum_geometric_of_lt_one hR0 hR1]
      simp only [R]
      field_simp

/-- Real-valued form of the recursive reverse majorant. -/
def realReverseMajorant {N : ℕ} (theta : ℝ) (c : Composition N) : ℝ :=
  (reverseMomentMajorant theta c.blocks.reverse : ℝ)

theorem realReverseMajorant_eq_series
    {N s : ℕ} (theta : ℝ) (c : Composition N)
    (hc : c ∈ fixedSet N s) :
    realReverseMajorant theta c =
      (∑ r ∈ Ico 1 (s + 1), realReverseMomentTerm theta c r) +
        (((3 : ℝ) ^ theta) ^ s /
          (((2 : ℝ) ^ N) ^ theta)) := by
  have hlen : c.length = s := (Finset.mem_filter.mp hc).2
  have hsum : c.blocks.sum = N := c.blocks_sum
  unfold realReverseMajorant
  rw [reverseMomentMajorant_eq_series]
  unfold reverseMomentSeries
  push_cast
  rw [List.length_reverse, c.blocks_length, hlen,
    List.sum_reverse, hsum]
  rw [Finset.sum_Ico_eq_sum_range]
  apply congrArg₂ (· + ·)
  · apply sum_congr rfl
    intro i hi
    have hir : 0 < i + 1 := Nat.succ_pos i
    simpa [Nat.add_comm] using
      (coe_reverseMomentTerm_eq_realReverseMomentTerm
        (theta := theta) c (r := i + 1) hir)
  · rfl

theorem rpow_nat_div_rpow_nat_le_one
    {a b : ℕ} {theta : ℝ} (htheta : 0 ≤ theta)
    (hb : 0 < b) (hab : a ≤ b) :
    ((a : ℝ) ^ theta) / ((b : ℝ) ^ theta) ≤ 1 := by
  rw [div_le_one (Real.rpow_pos_of_pos (by positivity) _)]
  exact Real.rpow_le_rpow (Nat.cast_nonneg a) (by exact_mod_cast hab) htheta

/-- Once the multiplicative coefficient is contracting, the final exposed
reverse prefix and the remaining tail each cost at most one. -/
theorem realReverseMajorant_le_nonterminal_add_two
    {N s : ℕ} {theta : ℝ}
    (htheta : 0 ≤ theta) (hs0 : 0 < s)
    (hcontract : 3 ^ s ≤ 2 ^ N)
    (c : Composition N) (hc : c ∈ fixedSet N s) :
    realReverseMajorant theta c ≤
      (∑ r ∈ Ico 1 s, realReverseMomentTerm theta c r) + 2 := by
  have hseries := realReverseMajorant_eq_series theta c hc
  have hspend : reverseSpend c s = N := by
    have hlen : c.length = s := (Finset.mem_filter.mp hc).2
    simp [reverseSpend, terminalBlocks, hlen, c.blocks_sum]
  have hpowSmall : 3 ^ (s - 1) ≤ 2 ^ N := by
    exact (pow_le_pow_right₀ (by norm_num : 1 ≤ (3 : ℕ)) (Nat.sub_le s 1)).trans
      hcontract
  have hlast : realReverseMomentTerm theta c s ≤ 1 := by
    unfold realReverseMomentTerm
    rw [hspend,
      ← natPow_rpow_eq_rpow_natPow (by norm_num : (0 : ℝ) ≤ 3)]
    simpa [Nat.cast_pow] using
      (rpow_nat_div_rpow_nat_le_one htheta (by positivity) hpowSmall)
  have htail :
      (((3 : ℝ) ^ theta) ^ s /
        (((2 : ℝ) ^ N) ^ theta)) ≤ 1 := by
    rw [← natPow_rpow_eq_rpow_natPow (by norm_num : (0 : ℝ) ≤ 3)]
    simpa [Nat.cast_pow] using
      (rpow_nat_div_rpow_nat_le_one htheta (by positivity) hcontract)
  rw [hseries, Nat.Ico_succ_right_eq_insert_Ico (by omega : 1 ≤ s),
    sum_insert (by simp)]
  linarith

/-- Average of the recursive reverse majorant over one fixed level. -/
def fixedReverseMajorantAverage
    (N s : ℕ) (theta : ℝ) : ℝ :=
  (∑ c ∈ fixedSet N s, realReverseMajorant theta c) /
    ((fixedSet N s).card : ℝ)

/-- Central reverse-spend moment bound before making its constant uniform
over a prescribed central window. -/
theorem fixedReverseMajorantAverage_le
    {N s : ℕ} {theta : ℝ}
    (htheta0 : 0 < theta)
    (hN : 1 < N) (hs1 : 1 < s) (hsN : s < N)
    (hpiAlpha :
      centralSeparatorProportion N s < centralRenyiAlpha theta)
    (hcontract : 3 ^ s ≤ 2 ^ N) :
    fixedReverseMajorantAverage N s theta ≤
      (N : ℝ) * (3 : ℝ) ^ (-theta) /
        (1 - centralRenyiRatio theta
          (centralSeparatorProportion N s)) + 2 := by
  have hcard : 0 < ((fixedSet N s).card : ℝ) := by
    rw [card_fixedSet N s (by omega) (by omega)]
    exact_mod_cast Nat.choose_pos (by omega : s - 1 ≤ N - 1)
  have hpoint :
      (∑ c ∈ fixedSet N s, realReverseMajorant theta c) ≤
        fixedReverseNonterminalSum N s theta +
          2 * ((fixedSet N s).card : ℝ) := by
    calc
      (∑ c ∈ fixedSet N s, realReverseMajorant theta c) ≤
          ∑ c ∈ fixedSet N s,
            ((∑ r ∈ Ico 1 s, realReverseMomentTerm theta c r) + 2) := by
        apply sum_le_sum
        intro c hc
        exact realReverseMajorant_le_nonterminal_add_two
          htheta0.le (by omega) hcontract c hc
      _ = fixedReverseNonterminalSum N s theta +
          2 * ((fixedSet N s).card : ℝ) := by
        simp only [sum_add_distrib, sum_const, card_attach, nsmul_eq_mul]
        unfold fixedReverseNonterminalSum fixedReverseTermSum
        rw [Finset.sum_comm]
        ring
  unfold fixedReverseMajorantAverage
  calc
    (∑ c ∈ fixedSet N s, realReverseMajorant theta c) /
          ((fixedSet N s).card : ℝ) ≤
        (fixedReverseNonterminalSum N s theta +
          2 * ((fixedSet N s).card : ℝ)) /
            ((fixedSet N s).card : ℝ) :=
      div_le_div_of_nonneg_right hpoint hcard.le
    _ = fixedReverseNonterminalSum N s theta /
          ((fixedSet N s).card : ℝ) + 2 := by
      field_simp
    _ ≤ (N : ℝ) * (3 : ℝ) ^ (-theta) /
        (1 - centralRenyiRatio theta
          (centralSeparatorProportion N s)) + 2 := by
      exact add_le_add_right
        (fixedReverseNonterminalSum_div_card_le
          htheta0 hN hs1 hsN hpiAlpha) 2

end

end FixedTotal

end CollatzEndpointTransport
/-
Central fixed-total higher-Renyi moment bound.

The quotient-order estimate is normalized by the dyadic spend and then
combined with the reverse-spend average.  This file keeps the exact
fixed-level probability factor visible for the later shell mixture.
-/

namespace CollatzEndpointTransport

namespace FixedTotal

open Nat Finset
open scoped Real NNReal

noncomputable section

/-- Probability of a fixed length in the uniform composition model. -/
def fixedLengthProbability (N s : ℕ) : ℝ :=
  ((fixedSet N s).card : ℝ) / (2 : ℝ) ^ (N - 1)

/-- Real form of the pointwise normalized reverse-spend majorization. -/
theorem real_normalized_fixed_lift_le_majorant
    {N s : ℕ} {theta : ℝ}
    (htheta0 : 0 ≤ theta) (htheta1 : theta ≤ 1)
    (c : Composition N) (hc : c ∈ fixedSet N s) :
    (((((3 ^ s + syracuseNumerator c : ℕ) : ℝ) /
          (2 : ℝ) ^ N)) ^ theta) ≤
      realReverseMajorant theta c := by
  have hlen : c.length = s := (Finset.mem_filter.mp hc).2
  have h := normalized_fixed_lift_rpow_le_majorant
    c htheta0 htheta1
  have hcast :
      (((((3 ^ c.length + syracuseNumerator c : ℕ) : ℝ≥0) /
          ((2 : ℝ≥0) ^ N)) ^ theta : ℝ≥0) : ℝ) ≤
        (reverseMomentMajorant theta c.blocks.reverse : ℝ) := by
    exact_mod_cast h
  simpa [realReverseMajorant, hlen, Nat.cast_add, Nat.cast_pow] using hcast

/-- Unnormalized pointwise lift bound. -/
theorem real_fixed_lift_le_scale_mul_majorant
    {N s : ℕ} {theta : ℝ}
    (htheta0 : 0 ≤ theta) (htheta1 : theta ≤ 1)
    (c : Composition N) (hc : c ∈ fixedSet N s) :
    (((3 ^ s + syracuseNumerator c : ℕ) : ℝ) ^ theta) ≤
      (((2 : ℝ) ^ N) ^ theta) * realReverseMajorant theta c := by
  have h := real_normalized_fixed_lift_le_majorant
    htheta0 htheta1 c hc
  rw [Real.div_rpow (by positivity) (by positivity)] at h
  have h' := (div_le_iff₀ (Real.rpow_pos_of_pos (by positivity) _)).mp h
  simpa [mul_comm] using h'

/-- The normalized source-side lift moment is controlled by the average
recursive majorant. -/
theorem fixedLiftMoment_div_scale_card_le
    {N s : ℕ} {theta : ℝ}
    (htheta0 : 0 ≤ theta) (htheta1 : theta ≤ 1)
    (hcard : 0 < (fixedSet N s).card) :
    fixedLiftMoment N s theta /
        ((((2 : ℝ) ^ N) ^ theta) * ((fixedSet N s).card : ℝ)) ≤
      fixedReverseMajorantAverage N s theta := by
  have hden :
      0 < (((2 : ℝ) ^ N) ^ theta) * ((fixedSet N s).card : ℝ) := by
    exact mul_pos (Real.rpow_pos_of_pos (by positivity) _)
      (by exact_mod_cast hcard)
  unfold fixedLiftMoment fixedReverseMajorantAverage
  apply (div_le_div_iff₀ hden (by exact_mod_cast hcard :
    (0 : ℝ) < (fixedSet N s).card)).2
  calc
    (∑ c ∈ fixedSet N s,
        (((3 ^ s + syracuseNumerator c : ℕ) : ℝ) ^ theta)) *
          ((fixedSet N s).card : ℝ) ≤
        (∑ c ∈ fixedSet N s,
          (((2 : ℝ) ^ N) ^ theta) * realReverseMajorant theta c) *
            ((fixedSet N s).card : ℝ) := by
      exact mul_le_mul_of_nonneg_right
        (sum_le_sum fun c hc =>
          real_fixed_lift_le_scale_mul_majorant htheta0 htheta1 c hc)
        (Nat.cast_nonneg _)
    _ = ((((2 : ℝ) ^ N) ^ theta) *
          ((fixedSet N s).card : ℝ)) *
        (∑ c ∈ fixedSet N s, realReverseMajorant theta c) := by
      rw [← Finset.mul_sum]
      ring
    _ = (∑ c ∈ fixedSet N s, realReverseMajorant theta c) *
        ((((2 : ℝ) ^ N) ^ theta) *
          ((fixedSet N s).card : ℝ)) := by ring

/-- Fixed-level Renyi moment in terms of the exact reverse-spend average. -/
theorem fixedRenyiMoment_le_reverseAverage
    {N s : ℕ} {theta : ℝ}
    (htheta0 : 0 < theta) (htheta1 : theta ≤ 1)
    (hcard : 0 < (fixedSet N s).card) :
    fixedRenyiMoment N s theta ≤
      4 * (((2 : ℝ) ^ N) ^ theta) *
        fixedReverseMajorantAverage N s theta /
          (((fixedSet N s).card : ℝ) ^ theta) := by
  have hlift := fixedLiftMoment_div_scale_card_le
    htheta0.le htheta1 hcard
  have hscale : 0 < (((2 : ℝ) ^ N) ^ theta) :=
    Real.rpow_pos_of_pos (by positivity) _
  have hcardR : 0 < ((fixedSet N s).card : ℝ) := by exact_mod_cast hcard
  have hlift' :
      fixedLiftMoment N s theta ≤
        (((2 : ℝ) ^ N) ^ theta) *
          ((fixedSet N s).card : ℝ) *
            fixedReverseMajorantAverage N s theta := by
      have hraw := (div_le_iff₀ (mul_pos hscale hcardR)).mp hlift
      simpa [mul_comm, mul_left_comm, mul_assoc] using hraw
  calc
    fixedRenyiMoment N s theta ≤
        4 * fixedLiftMoment N s theta /
          ((fixedSet N s).card : ℝ) ^ (1 + theta) :=
      fixedRenyiMoment_le N s htheta0 htheta1
    _ ≤ 4 * ((((2 : ℝ) ^ N) ^ theta) *
          ((fixedSet N s).card : ℝ) *
            fixedReverseMajorantAverage N s theta) /
          ((fixedSet N s).card : ℝ) ^ (1 + theta) := by
      exact div_le_div_of_nonneg_right
        (mul_le_mul_of_nonneg_left hlift' (by norm_num))
        (Real.rpow_nonneg (by positivity) _)
    _ = 4 * (((2 : ℝ) ^ N) ^ theta) *
        fixedReverseMajorantAverage N s theta /
          (((fixedSet N s).card : ℝ) ^ theta) := by
      rw [show (1 : ℝ) + theta = theta + 1 by ring,
        Real.rpow_add_one hcardR.ne']
      field_simp
      ring

/-- Central fixed-level moment with explicit geometric denominator. -/
theorem fixedRenyiMoment_central_le
    {N s : ℕ} {theta : ℝ}
    (htheta0 : 0 < theta) (htheta1 : theta ≤ 1)
    (hN : 1 < N) (hs1 : 1 < s) (hsN : s < N)
    (hpiAlpha :
      centralSeparatorProportion N s < centralRenyiAlpha theta)
    (hcontract : 3 ^ s ≤ 2 ^ N) :
    fixedRenyiMoment N s theta ≤
      4 * (((2 : ℝ) ^ N) ^ theta) /
          (((fixedSet N s).card : ℝ) ^ theta) *
        ((N : ℝ) * (3 : ℝ) ^ (-theta) /
          (1 - centralRenyiRatio theta
            (centralSeparatorProportion N s)) + 2) := by
  have hcard : 0 < (fixedSet N s).card := by
    rw [card_fixedSet N s (by omega) (by omega)]
    exact Nat.choose_pos (by omega)
  have hbase := fixedRenyiMoment_le_reverseAverage
    htheta0 htheta1 hcard
  have havg := fixedReverseMajorantAverage_le
    htheta0 hN hs1 hsN hpiAlpha hcontract
  calc
    fixedRenyiMoment N s theta ≤
        4 * (((2 : ℝ) ^ N) ^ theta) *
          fixedReverseMajorantAverage N s theta /
            (((fixedSet N s).card : ℝ) ^ theta) := hbase
    _ ≤ 4 * (((2 : ℝ) ^ N) ^ theta) *
          ((N : ℝ) * (3 : ℝ) ^ (-theta) /
            (1 - centralRenyiRatio theta
              (centralSeparatorProportion N s)) + 2) /
            (((fixedSet N s).card : ℝ) ^ theta) := by
      gcongr
    _ = 4 * (((2 : ℝ) ^ N) ^ theta) /
          (((fixedSet N s).card : ℝ) ^ theta) *
        ((N : ℝ) * (3 : ℝ) ^ (-theta) /
          (1 - centralRenyiRatio theta
            (centralSeparatorProportion N s)) + 2) := by ring

end

end FixedTotal

end CollatzEndpointTransport
/-
Uniform central-window inequalities for the higher-Renyi argument.

The paper's central condition is expressed with the real center
`(N+1)/2`.  Two explicit finite-size inequalities place the separator
proportion below the fixed interior value `piStar` and the odd-count
proportion below the multiplicative contraction boundary.  Keeping these
conditions explicit avoids hiding an unproved "sufficiently large N".
-/

namespace CollatzEndpointTransport

namespace FixedTotal

open scoped Real

noncomputable section

/-- Symmetric central window for the number of composition parts. -/
def InCentralRenyiWindow (N s : ℕ) (eta : ℝ) : Prop :=
  |(s : ℝ) - ((N : ℝ) + 1) / 2| ≤ eta * N

theorem central_window_upper
    {N s : ℕ} {eta : ℝ}
    (hcen : InCentralRenyiWindow N s eta) :
    (s : ℝ) ≤ (1 / 2 + eta) * N + 1 / 2 := by
  unfold InCentralRenyiWindow at hcen
  have hupper := (abs_le.mp hcen).2
  push_cast at hupper
  linarith

theorem central_window_lower
    {N s : ℕ} {eta : ℝ}
    (hcen : InCentralRenyiWindow N s eta) :
    (1 / 2 - eta) * N + 1 / 2 ≤ (s : ℝ) := by
  unfold InCentralRenyiWindow at hcen
  have hlower := (abs_le.mp hcen).1
  push_cast at hlower
  linarith

/-- An explicit finite-size condition places every central separator
proportion below the fixed interior value `piStar`. -/
theorem centralSeparatorProportion_le_piStar
    {N s : ℕ} {theta eta : ℝ}
    (hN : 1 < N) (hs : 0 < s)
    (hcen : InCentralRenyiWindow N s eta)
    (hsize :
      2 * eta ≤ centralRenyiGap theta eta * ((N : ℝ) - 1)) :
    centralSeparatorProportion N s ≤ centralRenyiPiStar theta eta := by
  have hNcast : (1 : ℝ) < (N : ℝ) := by exact_mod_cast hN
  have hden : 0 < (N : ℝ) - 1 := by linarith
  have hupper := central_window_upper hcen
  unfold centralRenyiGap at hsize
  unfold centralSeparatorProportion centralRenyiPiStar centralRenyiGap
  have hsCast : ((s - 1 : ℕ) : ℝ) = (s : ℝ) - 1 := by
    rw [Nat.cast_sub (by omega : 1 ≤ s)]
    norm_num
  have hNCast : ((N - 1 : ℕ) : ℝ) = (N : ℝ) - 1 := by
    rw [Nat.cast_sub (by omega : 1 ≤ N)]
    norm_num
  rw [hsCast, hNCast]
  rw [div_le_iff₀ hden]
  nlinarith

/-- A second explicit finite-size condition places the central odd count
below the multiplicative contraction boundary `log 2 / log 3`. -/
theorem central_window_le_log_ratio
    {N s : ℕ} {eta : ℝ}
    (hcen : InCentralRenyiWindow N s eta)
    (hsize :
      (1 / 2 : ℝ) ≤
        (Real.log 2 / Real.log 3 - (1 / 2 + eta)) * N) :
    (s : ℝ) ≤ (Real.log 2 / Real.log 3) * N := by
  have hupper := central_window_upper hcen
  linarith

theorem three_pow_le_two_pow_of_cast_le_log_ratio
    {N s : ℕ}
    (h : (s : ℝ) ≤ (Real.log 2 / Real.log 3) * N) :
    3 ^ s ≤ 2 ^ N := by
  have hlog2 : 0 < Real.log 2 := Real.log_pos (by norm_num)
  have hlog3 : 0 < Real.log 3 := Real.log_pos (by norm_num)
  have hlogs : (s : ℝ) * Real.log 3 ≤ (N : ℝ) * Real.log 2 := by
    have := mul_le_mul_of_nonneg_right h hlog3.le
    field_simp [hlog3.ne'] at this
    nlinarith
  have hexp := Real.exp_le_exp.mpr hlogs
  have hreal : (3 : ℝ) ^ s ≤ (2 : ℝ) ^ N := by
    calc
      (3 : ℝ) ^ s = Real.exp ((s : ℝ) * Real.log 3) := by
        symm
        rw [Real.exp_nat_mul, Real.exp_log (by norm_num : (0 : ℝ) < 3)]
      _ ≤ Real.exp ((N : ℝ) * Real.log 2) := hexp
      _ = (2 : ℝ) ^ N := by
        rw [Real.exp_nat_mul, Real.exp_log (by norm_num : (0 : ℝ) < 2)]
  exact_mod_cast hreal

/-- Uniform central fixed-level moment with the geometric denominator
replaced by the fixed interior ratio. -/
theorem fixedRenyiMoment_central_uniform_le
    {N s : ℕ} {theta eta : ℝ}
    (htheta0 : 0 < theta) (htheta1 : theta < 1)
    (heta0 : 0 < eta)
    (heta1 : eta < centralRenyiAlpha theta - 1 / 2)
    (hN : 1 < N) (hs1 : 1 < s) (hsN : s < N)
    (hcen : InCentralRenyiWindow N s eta)
    (hsizePi :
      2 * eta ≤ centralRenyiGap theta eta * ((N : ℝ) - 1))
    (hsizeDrift :
      (1 / 2 : ℝ) ≤
        (Real.log 2 / Real.log 3 - (1 / 2 + eta)) * N) :
    fixedRenyiMoment N s theta ≤
      4 * (((2 : ℝ) ^ N) ^ theta) /
          (((fixedSet N s).card : ℝ) ^ theta) *
        ((N : ℝ) * (3 : ℝ) ^ (-theta) /
          (1 - centralRenyiRatio theta
            (centralRenyiPiStar theta eta)) + 2) := by
  have hpi := centralSeparatorProportion_le_piStar hN (by omega) hcen hsizePi
  have hpi0 : 0 < centralSeparatorProportion N s := by
    unfold centralSeparatorProportion
    exact div_pos (Nat.cast_pos.mpr (Nat.sub_pos_of_lt hs1))
      (Nat.cast_pos.mpr (Nat.sub_pos_of_lt hN))
  have hpiAlpha := hpi.trans_lt (centralRenyiPiStar_lt_alpha heta1)
  have hcontract := three_pow_le_two_pow_of_cast_le_log_ratio
    (central_window_le_log_ratio hcen hsizeDrift)
  have hbase := fixedRenyiMoment_central_le htheta0 htheta1.le
    hN hs1 hsN hpiAlpha hcontract
  have hratio := centralRenyiRatio_mono htheta0 hpi0.le hpi
  have hstarlt := centralRenyiRatio_piStar_lt_one
    htheta0 htheta1
    heta0 heta1
  have hden0 : 0 < 1 - centralRenyiRatio theta
      (centralSeparatorProportion N s) := by
    linarith [centralRenyiRatio_lt_one htheta0 hpi0 hpiAlpha]
  have hdenStar : 0 < 1 - centralRenyiRatio theta
      (centralRenyiPiStar theta eta) := by linarith
  have hdenLe :
      1 - centralRenyiRatio theta (centralRenyiPiStar theta eta) ≤
        1 - centralRenyiRatio theta
          (centralSeparatorProportion N s) := by
    linarith
  have hfrac :
      (N : ℝ) * (3 : ℝ) ^ (-theta) /
          (1 - centralRenyiRatio theta
            (centralSeparatorProportion N s)) ≤
        (N : ℝ) * (3 : ℝ) ^ (-theta) /
          (1 - centralRenyiRatio theta
            (centralRenyiPiStar theta eta)) := by
    exact div_le_div_of_nonneg_left (by positivity) hdenStar hdenLe
  calc
    fixedRenyiMoment N s theta ≤
        4 * (((2 : ℝ) ^ N) ^ theta) /
            (((fixedSet N s).card : ℝ) ^ theta) *
          ((N : ℝ) * (3 : ℝ) ^ (-theta) /
            (1 - centralRenyiRatio theta
              (centralSeparatorProportion N s)) + 2) := hbase
    _ ≤ 4 * (((2 : ℝ) ^ N) ^ theta) /
            (((fixedSet N s).card : ℝ) ^ theta) *
          ((N : ℝ) * (3 : ℝ) ^ (-theta) /
            (1 - centralRenyiRatio theta
              (centralRenyiPiStar theta eta)) + 2) := by
      exact mul_le_mul_of_nonneg_left (by linarith) (by positivity)

end

end FixedTotal

end CollatzEndpointTransport
/-
Polynomial aggregate central higher-Renyi moment.

The paper records the sharper exponent `N^(1+theta)`.  The formalized
endpoint theorem only needs a fixed polynomial, so this module uses the
elementary bound `p^(1-theta) <= 1` and obtains `O((N+1)^2)`.  This does
not change the exponential shell rate or the final endpoint constant.
-/

namespace CollatzEndpointTransport

namespace FixedTotal

open Nat Finset
open scoped Real

noncomputable section

/-- Source weight of one fixed-total composition level inside all `2^N`
Boolean words. -/
def fixedSourceWeight (N s : ℕ) : ℝ :=
  ((fixedSet N s).card : ℝ) / (2 : ℝ) ^ N

/-- Lengths in the prescribed central window. -/
def centralLengthSet (N : ℕ) (eta : ℝ) : Finset ℕ := by
  classical
  exact (Finset.Icc 1 N).filter fun s => InCentralRenyiWindow N s eta

/-- A fixed constant bounding the reverse-spend average throughout the
central window. -/
def centralMomentConstant (theta eta : ℝ) : ℝ :=
  4 * ((3 : ℝ) ^ (-theta) /
      (1 - centralRenyiRatio theta (centralRenyiPiStar theta eta)) + 2)

theorem fixedSet_card_le_two_pow
    (N s : ℕ) :
    (fixedSet N s).card ≤ 2 ^ N := by
  calc
    (fixedSet N s).card ≤ Fintype.card (Composition N) :=
      Finset.card_le_univ _
    _ = 2 ^ (N - 1) := composition_card N
    _ ≤ 2 ^ N := pow_le_pow_right' (by norm_num : (1 : ℕ) ≤ 2)
      (Nat.sub_le N 1)

theorem fixedSourceWeight_nonneg
    (N s : ℕ) :
    0 ≤ fixedSourceWeight N s := by
  unfold fixedSourceWeight
  positivity

theorem fixedSourceWeight_le_one
    (N s : ℕ) :
    fixedSourceWeight N s ≤ 1 := by
  unfold fixedSourceWeight
  rw [div_le_one (by positivity : (0 : ℝ) < (2 : ℝ) ^ N)]
  exact_mod_cast fixedSet_card_le_two_pow N s

theorem source_weight_scale_eq
    {N s : ℕ} {theta : ℝ}
    (hcard : 0 < (fixedSet N s).card)
    (htheta : theta < 1) :
    fixedSourceWeight N s *
        ((((2 : ℝ) ^ N) ^ theta) /
          (((fixedSet N s).card : ℝ) ^ theta)) =
      (fixedSourceWeight N s) ^ (1 - theta) := by
  have hcardR : 0 < ((fixedSet N s).card : ℝ) := Nat.cast_pos.mpr hcard
  have hpow : 0 < (2 : ℝ) ^ N := by positivity
  have hweight : 0 < fixedSourceWeight N s :=
    div_pos hcardR hpow
  rw [Real.rpow_one_sub' hweight.le (by linarith)]
  unfold fixedSourceWeight
  rw [Real.div_rpow hcardR.le hpow.le]
  field_simp [hcardR.ne', hpow.ne',
    (Real.rpow_pos_of_pos hcardR _).ne',
    (Real.rpow_pos_of_pos hpow _).ne']

theorem source_weight_scale_le_one
    {N s : ℕ} {theta : ℝ}
    (hcard : 0 < (fixedSet N s).card)
    (htheta0 : 0 < theta) (htheta1 : theta < 1) :
    fixedSourceWeight N s *
        ((((2 : ℝ) ^ N) ^ theta) /
          (((fixedSet N s).card : ℝ) ^ theta)) ≤ 1 := by
  rw [source_weight_scale_eq hcard htheta1]
  exact Real.rpow_le_one
    (fixedSourceWeight_nonneg N s)
    (fixedSourceWeight_le_one N s)
    (by linarith)

theorem centralMomentConstant_pos
    {theta eta : ℝ}
    (htheta0 : 0 < theta) (htheta1 : theta < 1)
    (heta0 : 0 < eta)
    (heta1 : eta < centralRenyiAlpha theta - 1 / 2) :
    0 < centralMomentConstant theta eta := by
  have hratio := centralRenyiRatio_piStar_lt_one
    htheta0 htheta1 heta0 heta1
  have hden : 0 < 1 -
      centralRenyiRatio theta (centralRenyiPiStar theta eta) := by
    linarith
  unfold centralMomentConstant
  exact mul_pos (by norm_num)
    (add_pos_of_pos_of_nonneg (div_pos (by positivity) hden) (by norm_num))

/-- One central level, weighted by its exact source probability. -/
theorem fixedSourceWeight_mul_fixedRenyiMoment_le
    {N s : ℕ} {theta eta : ℝ}
    (htheta0 : 0 < theta) (htheta1 : theta < 1)
    (heta0 : 0 < eta)
    (heta1 : eta < centralRenyiAlpha theta - 1 / 2)
    (hN : 1 < N) (hs1 : 1 < s) (hsN : s < N)
    (hcen : InCentralRenyiWindow N s eta)
    (hsizePi :
      2 * eta ≤ centralRenyiGap theta eta * ((N : ℝ) - 1))
    (hsizeDrift :
      (1 / 2 : ℝ) ≤
        (Real.log 2 / Real.log 3 - (1 / 2 + eta)) * N) :
    fixedSourceWeight N s * fixedRenyiMoment N s theta ≤
      centralMomentConstant theta eta * (N + 1) := by
  have hcard : 0 < (fixedSet N s).card := by
    rw [card_fixedSet N s (by omega) (by omega)]
    exact Nat.choose_pos (by omega)
  have hmoment := fixedRenyiMoment_central_uniform_le
    htheta0 htheta1 heta0 heta1 hN hs1 hsN hcen hsizePi hsizeDrift
  have hscale := source_weight_scale_le_one hcard htheta0 htheta1
  have hA0 : 0 ≤ (3 : ℝ) ^ (-theta) /
      (1 - centralRenyiRatio theta (centralRenyiPiStar theta eta)) := by
    have hratio := centralRenyiRatio_piStar_lt_one
      htheta0 htheta1 heta0 heta1
    exact div_nonneg (by positivity) (by linarith)
  have hA :
      (N : ℝ) * (3 : ℝ) ^ (-theta) /
          (1 - centralRenyiRatio theta (centralRenyiPiStar theta eta)) + 2 ≤
        (N + 1 : ℝ) *
          ((3 : ℝ) ^ (-theta) /
            (1 - centralRenyiRatio theta (centralRenyiPiStar theta eta)) + 2) := by
    have hN0 : 0 ≤ (N : ℝ) := Nat.cast_nonneg N
    calc
      (N : ℝ) * (3 : ℝ) ^ (-theta) /
            (1 - centralRenyiRatio theta (centralRenyiPiStar theta eta)) + 2 =
          (N : ℝ) *
            ((3 : ℝ) ^ (-theta) /
              (1 - centralRenyiRatio theta (centralRenyiPiStar theta eta))) + 2 := by
        ring
      _ ≤ ((N : ℝ) + 1) *
          ((3 : ℝ) ^ (-theta) /
            (1 - centralRenyiRatio theta (centralRenyiPiStar theta eta)) + 2) := by
        nlinarith
      _ = (N + 1 : ℝ) *
          ((3 : ℝ) ^ (-theta) /
            (1 - centralRenyiRatio theta (centralRenyiPiStar theta eta)) + 2) := by
        push_cast
        ring
  calc
    fixedSourceWeight N s * fixedRenyiMoment N s theta ≤
        fixedSourceWeight N s *
          (4 * ((((2 : ℝ) ^ N) ^ theta) /
              (((fixedSet N s).card : ℝ) ^ theta)) *
            ((N : ℝ) * (3 : ℝ) ^ (-theta) /
              (1 - centralRenyiRatio theta
                (centralRenyiPiStar theta eta)) + 2)) := by
      convert
        (mul_le_mul_of_nonneg_left hmoment
          (fixedSourceWeight_nonneg N s)) using 1 <;> ring
    _ ≤ 4 *
          ((N + 1 : ℝ) *
            ((3 : ℝ) ^ (-theta) /
              (1 - centralRenyiRatio theta
                (centralRenyiPiStar theta eta)) + 2)) := by
      have hfactor :
          fixedSourceWeight N s *
              ((((2 : ℝ) ^ N) ^ theta) /
                (((fixedSet N s).card : ℝ) ^ theta)) *
            ((N : ℝ) * (3 : ℝ) ^ (-theta) /
              (1 - centralRenyiRatio theta
                (centralRenyiPiStar theta eta)) + 2) ≤
          1 * ((N + 1 : ℝ) *
            ((3 : ℝ) ^ (-theta) /
              (1 - centralRenyiRatio theta
                (centralRenyiPiStar theta eta)) + 2)) := by
        have hcurrent :
            0 ≤ (N : ℝ) * (3 : ℝ) ^ (-theta) /
                (1 - centralRenyiRatio theta
                  (centralRenyiPiStar theta eta)) + 2 := by
          have hN0 : 0 ≤ (N : ℝ) := Nat.cast_nonneg N
          rw [show
            (N : ℝ) * (3 : ℝ) ^ (-theta) /
                (1 - centralRenyiRatio theta
                  (centralRenyiPiStar theta eta)) =
              (N : ℝ) *
                ((3 : ℝ) ^ (-theta) /
                  (1 - centralRenyiRatio theta
                    (centralRenyiPiStar theta eta))) by ring]
          nlinarith
        exact mul_le_mul hscale hA hcurrent zero_le_one
      nlinarith
    _ = centralMomentConstant theta eta * (N + 1) := by
      unfold centralMomentConstant
      push_cast
      ring

/-- Coarse aggregate central moment.  Its quadratic polynomial prefactor
is sufficient for the endpoint-only theorem. -/
theorem central_fixed_total_aggregate_le
    {N : ℕ} {theta eta : ℝ}
    (htheta0 : 0 < theta) (htheta1 : theta < 1)
    (heta0 : 0 < eta)
    (heta1 : eta < centralRenyiAlpha theta - 1 / 2)
    (hN : 3 < N)
    (hsizePi :
      2 * eta ≤ centralRenyiGap theta eta * ((N : ℝ) - 1))
    (hsizeDrift :
      (1 / 2 : ℝ) ≤
        (Real.log 2 / Real.log 3 - (1 / 2 + eta)) * N)
    (hinterior :
      ∀ s ∈ centralLengthSet N eta, 1 < s ∧ s < N) :
    (∑ s ∈ centralLengthSet N eta,
        fixedSourceWeight N s * fixedRenyiMoment N s theta) ≤
      centralMomentConstant theta eta * (N + 1) ^ 2 := by
  have hconst0 := (centralMomentConstant_pos
    htheta0 htheta1 heta0 heta1).le
  calc
    (∑ s ∈ centralLengthSet N eta,
        fixedSourceWeight N s * fixedRenyiMoment N s theta) ≤
      ∑ _s ∈ centralLengthSet N eta,
        centralMomentConstant theta eta * (N + 1) := by
      apply Finset.sum_le_sum
      intro s hs
      have hsData := hinterior s hs
      have hsMem :
          s ∈ Finset.Icc 1 N ∧ InCentralRenyiWindow N s eta := by
        simpa [centralLengthSet] using hs
      exact fixedSourceWeight_mul_fixedRenyiMoment_le
        htheta0 htheta1 heta0 heta1 (by omega)
        hsData.1 hsData.2 hsMem.2
        hsizePi hsizeDrift
    _ = (centralLengthSet N eta).card *
        (centralMomentConstant theta eta * (N + 1)) := by simp
    _ ≤ (N + 1 : ℝ) *
        (centralMomentConstant theta eta * (N + 1)) := by
      gcongr
      have hcard : (centralLengthSet N eta).card ≤ N + 1 := by
        have hsub : centralLengthSet N eta ⊆ Finset.range (N + 1) := by
          intro s hs
          have hsMem : s ∈ Finset.Icc 1 N := by
            have hboth :
                s ∈ Finset.Icc 1 N ∧ InCentralRenyiWindow N s eta := by
              simpa [centralLengthSet] using hs
            exact hboth.1
          exact Finset.mem_range.mpr
            (Nat.lt_succ_of_le (Finset.mem_Icc.mp hsMem).2)
        have hc := Finset.card_le_card hsub
        simpa using hc
      exact_mod_cast hcard
    _ = centralMomentConstant theta eta * (N + 1) ^ 2 := by ring

end

end FixedTotal

end CollatzEndpointTransport
