/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import CollatzEndpointTransport.Linear.OptimizedLinearPowerSchedule

/-!
# Optimized Linear Power Envelope

The concrete shell family generated by the optimized linear schedule.

This file connects the power schedule to the exact envelope induction.  It
also proves that the stage-zero density exponent tends to zero, so every
large shell lies in the small-density range where the nonlinear pullback
dominates the chosen linear transport constant.
-/

namespace CollatzEndpointTransport

namespace OptimizedLinearPullback

open scoped Real Topology

noncomputable section

open QuantitativeDensity

def powerR (s : ℝ) (M : ℕ) : ℕ :=
  powerStageCount s M

def powerTR (kappa q s : ℝ) (M : ℕ) : ℝ :=
  powerTerminalTolerance kappa q (powerR s M)

def powerEnvelope (q kappa s : ℝ) (M : ℕ) : Set ℕ :=
  EnvelopeGood
    (linearLambda q (powerR s M))
    (powerTR kappa q s M)

def powerEnvelopeC
    (q transport kappa s : ℝ) (M : ℕ) : ℝ :=
  linearC q transport (asymptoticEta transport)
    kappa (powerR s M) (powerTR kappa q s M) (powerR s M)

def powerEnvelopeD
    (q transport kappa s : ℝ) (M : ℕ) : ℝ :=
  linearD transport kappa
    (powerR s M) (powerTR kappa q s M) (powerR s M)

def powerEnvelopeD0
    (q transport kappa s : ℝ) (M : ℕ) : ℝ :=
  linearD transport kappa
    (powerR s M) (powerTR kappa q s M) 0

theorem powerEnvelopeD0_pos
    {q transport kappa s : ℝ}
    (htransport : 0 < transport)
    (hk : KappaAdmissible kappa)
    (hq0 : 0 < q) (hqa : a0 < q)
    (M : ℕ) :
    0 < powerEnvelopeD0 q transport kappa s M := by
  exact linearD_pos_all
    (R := powerR s M)
    htransport hk
    (powerTerminalTolerance_pos hk hq0 hqa _) 0

theorem powerEnvelopeD0_le_terminal_square
    {q transport kappa s : ℝ}
    (hk : KappaAdmissible kappa)
    (hq0 : 0 < q) (hqa : a0 < q)
    (M : ℕ) :
    powerEnvelopeD0 q transport kappa s M ≤
      Terras.maximalBarrierC0 / Real.log 2 *
        (powerTR kappa q s M) ^ 2 := by
  have ht0 := powerTerminalTolerance_pos hk hq0 hqa (powerR s M)
  have hkpow :
      kappa ^ powerR s M ≤ 1 :=
    pow_le_one₀ hk.1.le (kappa_le_one hk)
  have ht0nonneg : 0 ≤ powerTR kappa q s M := by
    exact ht0.le
  have hmul :
      kappa ^ powerR s M * powerTR kappa q s M ≤
        powerTR kappa q s M := by
    simpa [one_mul] using
      mul_le_mul_of_nonneg_right hkpow ht0nonneg
  have hsq :
      (kappa ^ powerR s M * powerTR kappa q s M) ^ 2 ≤
        (powerTR kappa q s M) ^ 2 := by
    simpa [pow_two] using
      mul_self_le_mul_self
        (mul_nonneg (pow_nonneg hk.1.le _) ht0nonneg) hmul
  unfold powerEnvelopeD0
  simp only [linearD_zero, linearTolerance, Nat.sub_zero]
  unfold Terras.quadraticWindowDensityRate
  have hcoef :
      0 ≤ Terras.maximalBarrierC0 / Real.log 2 :=
    (div_pos Terras.maximalBarrierC0_pos
      (Real.log_pos (by norm_num))).le
  calc
    Terras.maximalBarrierC0 *
          (kappa ^ powerR s M * powerTR kappa q s M) ^ 2 /
          Real.log 2 =
        (Terras.maximalBarrierC0 / Real.log 2) *
          (kappa ^ powerR s M * powerTR kappa q s M) ^ 2 := by ring
    _ ≤ (Terras.maximalBarrierC0 / Real.log 2) *
          (powerTR kappa q s M) ^ 2 :=
      mul_le_mul_of_nonneg_left hsq hcoef

theorem powerEnvelopeD0_tendsto_zero
    {q transport kappa s : ℝ}
    (htransport : 0 < transport)
    (hk : KappaAdmissible kappa)
    (hq0 : 0 < q) (hqa : a0 < q) (hq1 : q < 1)
    (hs : 0 < s) :
    Filter.Tendsto
      (powerEnvelopeD0 q transport kappa s)
      Filter.atTop (nhds 0) := by
  have ht :=
    powerTerminalTolerance_tendsto_zero
      hk hq0 hqa hq1 hs
  have hsq := ht.pow 2
  have hmodel :=
    hsq.const_mul (Terras.maximalBarrierC0 / Real.log 2)
  exact squeeze_zero
    (fun M => (powerEnvelopeD0_pos htransport hk hq0 hqa M).le)
    (fun M => powerEnvelopeD0_le_terminal_square hk hq0 hqa M)
    (by
      simpa [powerTR, powerR, Function.comp_apply] using hmodel)

theorem powerEnvelopeD0_eventually_le
    {q transport kappa s Dcut : ℝ}
    (htransport : 0 < transport)
    (hk : KappaAdmissible kappa)
    (hq0 : 0 < q) (hqa : a0 < q) (hq1 : q < 1)
    (hs : 0 < s) (hDcut : 0 < Dcut) :
    ∀ᶠ M : ℕ in Filter.atTop,
      powerEnvelopeD0 q transport kappa s M ≤ Dcut := by
  have ht :=
    powerEnvelopeD0_tendsto_zero
      htransport hk hq0 hqa hq1 hs
  have hevent :=
    (Metric.tendsto_atTop.1 ht) Dcut hDcut
  filter_upwards [Filter.eventually_atTop.2 hevent] with M hM
  rw [Real.dist_eq] at hM
  have hnonneg :=
    (powerEnvelopeD0_pos
      (s := s) htransport hk hq0 hqa M).le
  simpa [sub_zero, abs_of_nonneg hnonneg] using hM.le

/-- The concrete terminal envelope has the exact recursively generated
`(C_M,D_M)` density certificate once the stage-zero exponent is below the
small-density cutoff. -/
theorem powerEnvelope_dense
    {q transport kappa s Dcut : ℝ}
    (htransport0 : 0 < transport)
    (htransportLimit : transport < asymptoticRateLimit)
    (hk : KappaAdmissible kappa)
    (hq0 : 0 < q) (hqa : a0 < q) (hq1 : q < 1)
    (hDcut0 : 0 < Dcut) (hDcut1 : Dcut ≤ 1)
    (hcut :
      ∀ D : ℝ, 0 < D → D ≤ Dcut →
        transport * D ≤
          shellRate (asymptoticEta transport) D /
            Real.log 2)
    {M : ℕ}
    (hDzero :
      powerEnvelopeD0 q transport kappa s M ≤ Dcut) :
    IsCDDense
      (powerEnvelope q kappa s M)
      (powerEnvelopeC q transport kappa s M)
      (powerEnvelopeD q transport kappa s M) := by
  have ht0 :=
    powerTerminalTolerance_pos hk hq0 hqa (powerR s M)
  have ht1 :=
    powerTerminalTolerance_le_one hk hq0 hqa (powerR s M)
  have hcap :=
    powerTerminalTolerance_le_cap hk hq0 hqa (powerR s M)
  have hstage :=
    envelopeGood_dense_linear_stage
      (q := q) (transport := transport)
      (kappa := kappa) (tR := powerTR kappa q s M)
      (Dcut := Dcut) (R := powerR s M)
      htransport0 htransportLimit hk hq0 hqa hq1
      ht0 ht1 hcap hDcut0 hDcut1 hcut hDzero
      (powerR s M) le_rfl
  simpa [powerEnvelope, powerEnvelopeC, powerEnvelopeD,
    powerTR, powerR, linearTolerance] using hstage

theorem powerEnvelopeC_terminal_bound
    {q transport kappa s : ℝ}
    (htransport0 : 0 < transport)
    (htransportLimit : transport < asymptoticRateLimit)
    (hk : KappaAdmissible kappa)
    (hq0 : 0 < q) (hqa : a0 < q) (hq1 : q < 1)
    {M : ℕ}
    (hDterminal1 :
      powerEnvelopeD q transport kappa s M ≤ 1) :
    powerEnvelopeC q transport kappa s M + 2 ≤
      (linearStageK transport (asymptoticEta transport) *
          ((powerEnvelopeD q transport kappa s M)⁻¹) ^ 2 *
          Real.exp
            (linearStartupB q /
              linearLambda q (powerR s M))) ^ (powerR s M) *
      (Terras.quadraticWindowFixedGlobalConstant + 2) := by
  have htransport1 : transport ≤ 1 :=
    (htransportLimit.trans asymptoticRateLimit_lt_one).le
  exact linearC_terminal_bound
    htransport0 htransport1
    (asymptoticEta_pos htransport0)
    (asymptoticEta_lt_one htransportLimit)
    hk
    (powerTerminalTolerance_pos hk hq0 hqa _)
    hDterminal1 hq0 hqa hq1

end

end OptimizedLinearPullback

end CollatzEndpointTransport
