/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import CollatzEndpointTransport.Common.QuantitativePullbackDefs

/-!
# Quantitative Pullback Parameters

Scalar parameter package for the quantitative one-block pullback.

The choices are those audited against Inselmann's Lemmas 2.12, 2.16, 2.17,
and 2.18:

  eta       = D / 64,
  etaPrime  = D / 4,
  alpha     = 1/2 - eta,
  corrTol   = eta * log_2(3) / 2.

This file proves only real arithmetic.  In particular it does not assume or
prove cone robustness, base-map transport, or a Collatz orbit statement.
The point is to make every exponent loss and every startup threshold a named,
machine-checked lemma before the finite-set counting proof begins.
-/

namespace CollatzEndpointTransport

namespace QuantitativeDensity

open scoped Real

noncomputable section

def pullEta (D : ℝ) : ℝ := D / 64

def pullEtaPrime (D : ℝ) : ℝ := D / 4

def pullAlpha (D : ℝ) : ℝ := 1 / 2 - pullEta D

def pullCorrectionTol (D : ℝ) : ℝ :=
  pullEta D * lg3 / 2

def pullConeExponent (D : ℝ) : ℝ :=
  D * (1 + pullEtaPrime D) - 2 * pullEtaPrime D

theorem pullEta_pos {D : ℝ} (hD : 0 < D) :
    0 < pullEta D := by
  unfold pullEta
  positivity

theorem pullEtaPrime_pos {D : ℝ} (hD : 0 < D) :
    0 < pullEtaPrime D := by
  unfold pullEtaPrime
  positivity

theorem pullCorrectionTol_pos {D : ℝ} (hD : 0 < D) :
    0 < pullCorrectionTol D := by
  unfold pullCorrectionTol
  exact div_pos (mul_pos (pullEta_pos hD) lg3_pos) (by norm_num)

theorem pullEta_le_one_sixty_four {D : ℝ} (hD : D ≤ 1) :
    pullEta D ≤ 1 / 64 := by
  unfold pullEta
  linarith

theorem pullEta_le_half {D : ℝ} (hD : D ≤ 1) :
    pullEta D ≤ 1 / 2 := by
  have := pullEta_le_one_sixty_four hD
  linarith

theorem pullEtaPrime_le_quarter {D : ℝ} (hD : D ≤ 1) :
    pullEtaPrime D ≤ 1 / 4 := by
  unfold pullEtaPrime
  linarith

theorem pullAlpha_lt_half {D : ℝ} (hD : 0 < D) :
    pullAlpha D < 1 / 2 := by
  unfold pullAlpha
  linarith [pullEta_pos hD]

theorem pullAlpha_le_half {D : ℝ} (hD : 0 ≤ D) :
    pullAlpha D ≤ 1 / 2 := by
  unfold pullAlpha pullEta
  linarith

theorem pullAlpha_ge_thirty_one_sixty_four
    {D : ℝ} (hD : D ≤ 1) :
    31 / 64 ≤ pullAlpha D := by
  unfold pullAlpha pullEta
  linarith

theorem pullAlpha_pos {D : ℝ} (_hD0 : 0 < D) (hD1 : D ≤ 1) :
    0 < pullAlpha D := by
  have h := pullAlpha_ge_thirty_one_sixty_four hD1
  norm_num at h ⊢
  linarith

/-- The source admissibility condition `etaPrime < D/(2-D)`. -/
theorem pullEtaPrime_lt_cone_limit
    {D : ℝ} (hD0 : 0 < D) (hD1 : D ≤ 1) :
    pullEtaPrime D < D / (2 - D) := by
  have hden : 0 < 2 - D := by linarith
  unfold pullEtaPrime
  rw [div_lt_div_iff₀ (by norm_num : (0 : ℝ) < 4) hden]
  nlinarith

/-- Exact cone exponent generated by the robust-core count. -/
theorem pullConeExponent_eq (D : ℝ) :
    pullConeExponent D = D / 2 + D ^ 2 / 4 := by
  unfold pullConeExponent pullEtaPrime
  ring

theorem pullConeExponent_ge_half
    {D : ℝ} :
    D / 2 ≤ pullConeExponent D := by
  rw [pullConeExponent_eq]
  nlinarith [sq_nonneg D]

theorem pullConeExponent_le_three_quarters
    {D : ℝ} (hD0 : 0 ≤ D) (hD1 : D ≤ 1) :
    pullConeExponent D ≤ 3 * D / 4 := by
  rw [pullConeExponent_eq]
  nlinarith [sq_nonneg D, mul_nonneg hD0 (sub_nonneg.mpr hD1)]

/-- The parity surplus fits strictly inside the cone depth. -/
theorem two_pullEta_mul_lg3_lt_pullEtaPrime
    {D : ℝ} (hD : 0 < D) :
    2 * pullEta D * lg3 < pullEtaPrime D := by
  have hlg := lg3_lt_two
  unfold pullEta pullEtaPrime
  nlinarith

/-- The deterministic base-map exponent is bounded below by a fixed
multiple of the input density exponent. -/
theorem pull_base_density_exponent_lower
    {D : ℝ} (hD0 : 0 ≤ D) (hD1 : D ≤ 1) :
    (31 / 128) * D * lg3 ≤
      pullConeExponent D * pullAlpha D * lg3 := by
  have hCone := pullConeExponent_ge_half (D := D)
  have hAlpha := pullAlpha_ge_thirty_one_sixty_four hD1
  have hlg := lg3_pos
  have hDhalf : 0 ≤ D / 2 := by positivity
  calc
    (31 / 128) * D * lg3 =
        (D / 2) * (31 / 64) * lg3 := by ring
    _ ≤ (D / 2) * pullAlpha D * lg3 := by
      gcongr
    _ ≤ pullConeExponent D * pullAlpha D * lg3 := by
      gcongr

/-- Floor-sensitive cone-depth inequality.  The startup `14 <= D*M` is the
real form of `M >= 14/D`.  The proof retains the exact `1/128` slack found
in the independent audit. -/
theorem pull_cone_depth_startup
    {D M : ℝ} (_hD0 : 0 < D) (hD1 : D ≤ 1)
    (_hM0 : 0 ≤ M) (hstart : 14 ≤ D * M) :
    2 * pullEta D * M + 1 + 1 / 128 ≤
      pullEtaPrime D * (pullAlpha D * M - 1) := by
  have h24D : 0 ≤ 24 - D := by linarith
  have hprod :
      0 ≤ (D * M - 14) * (24 - D) :=
    mul_nonneg (sub_nonneg.mpr hstart) h24D
  unfold pullAlpha pullEta pullEtaPrime
  nlinarith

/-- The correction tolerance is exactly `D * log_2(3) / 128`. -/
theorem pullCorrectionTol_eq (D : ℝ) :
    pullCorrectionTol D = D * lg3 / 128 := by
  unfold pullCorrectionTol pullEta
  ring

end

end QuantitativeDensity

end CollatzEndpointTransport
