/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import CollatzEndpointTransport.QuadraticAppendix.Main

/-!
# Quadratic appendix axiom audit

Replay surface for the strengthened quadratic Collatz route.

Building this module checks the complete Lean chain from the maximal Boolean
barrier through the quadratic pullback and the scalar endpoint.  The
`#print axioms` commands make the trusted dependency set explicit.
-/

#print axioms CollatzEndpointTransport.Terras.barrierHitCount_le_exp
#print axioms CollatzEndpointTransport.Terras.affineCorrection_scaled_le_maximal
#print axioms CollatzEndpointTransport.Terras.initialWindowGood_dense_quadratic_fixed

#print axioms CollatzEndpointTransport.QuantitativeDensity.quadratic_pull_cone_depth_startup
#print axioms CollatzEndpointTransport.QuantitativeDensity.quadratic_pull_base_density_exponent_lower
#print axioms CollatzEndpointTransport.QuantitativeDensity.coneCore_dense_weakened
#print axioms CollatzEndpointTransport.QuantitativeDensity.card_shellBad_basePullback_le_rpow
#print axioms CollatzEndpointTransport.QuantitativeDensity.quadratic_witness_implies_collatzPullback_on_shell
#print axioms CollatzEndpointTransport.QuantitativeDensity.collatzPullback_dense_quadratic

#print axioms CollatzEndpointTransport.QuantitativeDensity.quadraticHeadlineExponent_eq
#print axioms CollatzEndpointTransport.QuantitativeDensity.quadraticAdmissibleExponent_tendsto_headline

#print axioms CollatzEndpointTransport.QuantitativeDensity.one_step_envelope_concatenation
#print axioms CollatzEndpointTransport.QuantitativeDensity.envelopeGood_dense_one_stage
#print axioms CollatzEndpointTransport.QuantitativeDensity.envelopeGood_dense_stage
#print axioms CollatzEndpointTransport.QuantitativeDensity.concrete_quadratic_bootstrap_bound

#print axioms CollatzEndpointTransport.QuantitativeDensity.hasNaturalDensityOne_assembleDyadic
#print axioms CollatzEndpointTransport.QuantitativeDensity.explicitShellExceptionalRatio_tendsto_zero
#print axioms CollatzEndpointTransport.QuantitativeDensity.explicitShellExceptionalRatio_eventually_le_model
#print axioms CollatzEndpointTransport.QuantitativeDensity.theoremBSet_hasNaturalDensityOne
#print axioms
  CollatzEndpointTransport.QuantitativeDensity.iterate_at_horizon_le_rpow_of_mem_terminal_envelope
#print axioms CollatzEndpointTransport.QuantitativeDensity.envelopeHorizon_le_natural_log_time
#print axioms CollatzEndpointTransport.QuantitativeDensity.inv_bConst_mul_log_two_lt_6953
#print axioms CollatzEndpointTransport.QuantitativeDensity.envelopeHorizon_lt_6953_log
#print axioms CollatzEndpointTransport.QuantitativeDensity.one_lt_iterate_of_le_envelopeSurvivalHorizon
#print axioms CollatzEndpointTransport.QuantitativeDensity.quantitativeQuadraticSurvival
#print axioms CollatzEndpointTransport.QuantitativeDensity.quantitativeQuadraticSurvival_exceptional_count
#print axioms CollatzEndpointTransport.QuantitativeDensity.modelShellDecay_eventually_le_threeQuarter
#print axioms CollatzEndpointTransport.QuantitativeDensity.card_badPrefix_assembleDyadic_le_threeQuarter_rate
#print axioms CollatzEndpointTransport.QuantitativeDensity.theoremBShell_eventually_le_threeQuarter_rate
#print axioms
  CollatzEndpointTransport.QuantitativeDensity.theoremBSet_badPrefix_eventually_le_threeQuarter_log
#print axioms
  CollatzEndpointTransport.QuantitativeDensity.quantitativeQuadraticSurvival_exceptional_count_threeQuarter
#print axioms CollatzEndpointTransport.QuantitativeDensity.quantitativeQuadraticTheoremB_one
#print axioms CollatzEndpointTransport.QuantitativeDensity.quantitativeQuadraticTheoremB_timed
#print axioms CollatzEndpointTransport.QuantitativeDensity.quantitativeQuadraticTheoremB_exceptional_count
#print axioms
  CollatzEndpointTransport.QuantitativeDensity.quantitativeQuadraticTheoremB_exceptional_count_threeQuarter
#print axioms CollatzEndpointTransport.QuantitativeDensity.quantitativeQuadraticTheoremB

#print axioms CollatzEndpointTransport.Terras.Tmin_le_iff_exists_iterate_le
#print axioms CollatzEndpointTransport.QuantitativeDensity.quantitativeQuadraticPropositionA

#print axioms CollatzEndpointTransport.QuantitativeCollatzMain.collatzMin_le_iff_exists_iterate_le
#print axioms CollatzEndpointTransport.QuantitativeCollatzMain.collatz_quantitative_natural_density_descent
#print axioms
  CollatzEndpointTransport.QuantitativeCollatzMain.collatz_quantitative_natural_density_descent_timed
#print axioms CollatzEndpointTransport.QuantitativeCollatzMain.collatz_quantitative_exceptional_count
#print axioms CollatzEndpointTransport.QuantitativeCollatzMain.collatz_quantitative_natural_density_survival
#print axioms CollatzEndpointTransport.QuantitativeCollatzMain.collatz_quantitative_survival_exceptional_count
#print axioms
  CollatzEndpointTransport.QuantitativeCollatzMain.collatz_one_hitting_time_gt_quantitativeSurvivalHorizon
#print axioms CollatzEndpointTransport.QuantitativeCollatzMain.collatz_diagonal_natural_density_descent
